
annotate_tables:
  - tablename: persons
    annotate:
      SPEC: annotate_persons
      DF: persons
      TABLES:
        - households
  - tablename: households
    annotate:
      SPEC: annotate_households
      DF: households
      TABLES:
        - persons
        - land_use
  - tablename: persons
    annotate:
      SPEC: annotate_persons_after_hh
      DF: persons
      TABLES:
        - households
  - tablename: persons
    annotate:
      SPEC: annotate_persons_workplace
      DF: persons
      TABLES:
        - land_use
  - tablename: households
    annotate:
      SPEC: annotate_households_workplace
      DF: households
      TABLES:
        - persons
