SPEC: trip_mode_choice.csv
COEFFICIENTS: trip_mode_choice_coeffs.csv

LOGIT_TYPE: NL

NESTS:
  name: root
  coefficient: 1.00
  alternatives:
      - name: AUTO
        coefficient: 0.72
        alternatives:
            - name: DRIVEALONE
              coefficient: 0.35
              alternatives:
                - DRIVEALONEFREE
                - DRIVEALONEPAY
            - name: SHAREDRIDE2
              coefficient: 0.35
              alternatives:
                - SHARED2FREE
                - SHARED2PAY
            - name: SHAREDRIDE3
              coefficient: 0.35
              alternatives:
                - SHARED3FREE
                - SHARED3PAY
      - name: NONMOTORIZED
        coefficient: 0.72
        alternatives:
          - WALK
          - BIKE
      - name: TRANSIT
        coefficient:  0.72
        alternatives:
            - name: WALKACCESS
              coefficient: 0.5
              alternatives:
              - WALK_LOC
              - WALK_LRF
              - WALK_EXP
              - WALK_HVY
              - WALK_COM
            - name: DRIVEACCESS
              coefficient: 0.5
              alternatives:
              - DRIVE_LOC
              - DRIVE_LRF
              - DRIVE_EXP
              - DRIVE_HVY
              - DRIVE_COM
      - name: RIDEHAIL
        coefficient: 0.36
        alternatives:
          - name: TNC_SINGLE
            coefficient: 1.0
            alternatives:
              - SINGLE_UBER
              - SINGLE_LYFT
              - SINGLE_CRUISE
          - name: TNC_SHARED
            coefficient: 1.0
            alternatives:
              - SHARED_UBER
              - SHARED_LYFT
              - SHARED_CRUISE

CONSTANTS:
  orig_col_name: origin
  dest_col_name: destination
  costPerMile: 18.29
  costShareSr2: 1.75
  costShareSr3: 2.50
  waitThresh: 10.00
  walkThresh: 1.00
  shortWalk: 0.333
  longWalk: 0.667
  walkSpeed: 3.00
  bikeThresh: 6.00
  bikeSpeed: 12.00
#    maxCbdAreaTypeThresh: 2
#    indivTour: 1.00000
#    upperEA: 5
#    upperAM: 10
#    upperMD: 15
#    upperPM: 19
  I_MODE_MAP:
    DRIVEALONEFREE: 1
    DRIVEALONEPAY: 2
    SHARED2FREE: 3
    SHARED2PAY: 4
    SHARED3FREE: 5
    SHARED3PAY: 6
    WALK: 7
    BIKE: 8
    WALK_LOC: 9
    WALK_LRF: 10
    WALK_EXP: 11
    WALK_HVY: 12
    WALK_COM: 13
    DRIVE_LOC: 14
    DRIVE_LRF: 15
    DRIVE_EXP: 16
    DRIVE_HVY: 17
    DRIVE_COM: 18
    SINGLE_UBER: 19
    SINGLE_LYFT: 20
    SINGLE_CRUISE: 21
    SHARED_UBER: 22
    SHARED_LYFT: 23
    SHARED_CRUISE: 24
  I_SOV_MODES: [1, 2]
  I_SR2_MODES: [3, 4]
  I_SR3P_MODES: [5, 6]
  I_AUTO_MODES: [1, 2, 3, 4, 5, 6]
  I_WALK_MODE: 7
  I_BIKE_MODE: 8
  I_WALK_TRANSIT_MODES: [9, 10, 11, 12, 13]
  I_DRIVE_TRANSIT_MODES: [14, 15, 16, 17, 18]
  I_RIDE_HAIL_MODES: [19,20,21,22,23,24]
  I_RIDEHAIL_SINGLE_MODES: [19,20,21]
  I_RIDEHAIL_SHARED_MODES: [22,23,24]
  # RIDEHAIL Settings
  Taxi_baseFare: 2.20
  Taxi_costPerMile: 2.30
  Taxi_costPerMinute: 0.10
  Taxi_waitTime_mean:
    1: 5.5
    2: 9.5
    3: 13.3
    4: 17.3
    5: 26.5
  Taxi_waitTime_sd: 
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
  TNC_single_uber_baseFare: 4.77
  TNC_single_uber_costPerMile: 1.07
  TNC_single_uber_costPerMinute: 0.28
  TNC_single_uber_costMinimum: 7.20
  TNC_single_uber_waitTime_mean:
    1: 3.0
    2: 6.3
    3: 8.4
    4: 8.5
    5: 10.3
  TNC_single_uber_waitTime_sd:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
  TNC_single_lyft_baseFare: 4.77
  TNC_single_lyft_costPerMile: 1.07
  TNC_single_lyft_costPerMinute: 0.28
  TNC_single_lyft_costMinimum: 7.20
  TNC_single_lyft_waitTime_mean:
    1: 3.0
    2: 6.3
    3: 8.4
    4: 8.5
    5: 10.3
    TNC_single_lyft_waitTime_sd:
      1: 0
      2: 0
      3: 0
      4: 0
      5: 0
  TNC_single_cruise_baseFare: 3.82
  TNC_single_cruise_costPerMile: 0.85
  TNC_single_cruise_costPerMinute: 0.22
  TNC_single_cruise_costMinimum: 5.70
  TNC_single_cruise_waitTime_mean:
    1: 3.0
    2: 6.3
    3: 8.4
    4: 8.5
    5: 10.3
  TNC_single_cruise_waitTime_sd:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
  TNC_shared_uber_baseFare: 3.59
  TNC_shared_uber_costPerMile: 0.75
  TNC_shared_uber_costPerMinute: 0.08
  TNC_shared_uber_costMinimum: 3.00
  TNC_shared_uber_IVTFactor: 1.0
  TNC_shared_uber_waitTime_mean:
    1: 5.0
    2: 8.0
    3: 11.0
    4: 15.0
    5: 15.0
  TNC_shared_uber_waitTime_sd:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
  TNC_shared_lyft_baseFare: 3.59
  TNC_shared_lyft_costPerMile: 0.75
  TNC_shared_lyft_costPerMinute: 0.08
  TNC_shared_lyft_costMinimum: 3.00
  TNC_shared_lyft_IVTFactor: 1.5
  TNC_shared_lyft_waitTime_mean:
    1: 5.0
    2: 8.0
    3: 11.0
    4: 15.0
    5: 15.0
  TNC_shared_lyft_waitTime_sd:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
  TNC_shared_cruise_baseFare: 2.87
  TNC_shared_cruise_costPerMile: 0.60
  TNC_shared_cruise_costPerMinute: 0.07
  TNC_shared_cruise_costMinimum: 2.40
  TNC_shared_cruise_IVTFactor: 1.5
  TNC_shared_cruise_waitTime_mean:
    1: 5.0
    2: 8.0
    3: 11.0
    4: 15.0
    5: 15.0
  TNC_shared_cruise_waitTime_sd:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
  min_waitTime: 0
  max_waitTime: 50
  TNC_missed_trip_penalty: 75
  SAV_ASC: -2.0
  SAV_ride_alone: True
  SAV_pooled: True
  TNC_cruise_operating_zones: [1, 3, 5, 12, 13, 15, 18, 20, 23, 2, 4, 10, 11, 14, 16, 17, 19, 21, 22, 108, 109, 110, 41, 39, 37, 35, 33, 28, 25, 24, 29, 6, 30, 8, 51, 44, 46, 71, 48, 75, 72, 74, 40, 38, 36, 34, 32, 27, 26, 31, 7, 9, 43, 50, 185, 69, 77, 78, 80, 87, 84, 82, 89, 107, 42, 93, 103, 101, 99, 95, 97, 129, 130, 111, 112, 116, 117, 120, 139, 143, 144, 145, 148, 121, 123, 125, 134, 137, 138, 152, 160, 165, 164, 163, 153, 156, 91, 175, 173, 172, 171, 170, 169, 133, 168, 167, 184, 186, 179, 180, 182, 45, 49, 47, 73, 70, 68, 86, 76, 79, 85, 88, 81, 83, 106, 105, 104, 94, 102, 100, 98, 96, 128, 127, 114, 113, 115, 118, 119, 141, 140, 147, 150, 122, 124, 126, 151, 135, 136, 161, 162, 159, 155, 154, 90, 176, 174, 92, 131, 132, 166, 177, 178, 142, 187, 188, 189, 181, 183, 66, 62, 57, 64, 60, 54, 52, 53, 190, 157, 146, 65, 58, 67, 63, 61, 59, 55, 56, 158, 149]


# so far, we can use the same spec as for non-joint tours
preprocessor:
  SPEC: trip_mode_choice_annotate_trips_preprocessor
  DF: df
  TABLES:
    - land_use
    - tours

#  - SPEC: trip_mode_choice_annotate_trips_preprocessor2
#    DF: df
#    TABLES:
#      - land_use

# to reduce memory needs filter chooser table to these fields
TOURS_MERGED_CHOOSER_COLUMNS:
  - hhsize
  - age
  - auto_ownership
  - number_of_participants
  - tour_category
  - parent_tour_id
  - tour_mode
  - duration
  - value_of_time
  - tour_type
  - free_parking_at_work


MODE_CHOICE_LOGSUM_COLUMN_NAME: mode_choice_logsum
